version: "3.9"

services:
    server:
        container_name: backend
        image: backend
        hostname: backend
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        env_file:
          - .env
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        depends_on:
            postgres:
              condition: service_healthy
        networks:
          - main

    nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./blade-runner.crt:/etc/ssl/blade-runner.crt
        - ./blade-runner-privateKey.key:/etc/ssl/blade-runner-privateKey.key
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - server
      networks:
        - main

    postgres:
      image: postgres:14
      restart: unless-stopped
      env_file:
        - .env
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - postgresdata:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
          - main

    pgadmin:
      image: dpage/pgadmin4:4.18
      env_file:
        - .env
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        - PGADMIN_LISTEN_PORT=80
      ports:
        - "${PG_EXT_PORT}:${PG_PORT}"
      volumes:
        - pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - main

volumes:
  postgresdata:
    external: false
  pgadmin:
    external: false

networks:
  main:
    driver: bridge
