export const CHANGE_LAYOUT_VIEW = 'CHANGE_LAYOUT_VIEW'

export const PLAYER_SCORE = 'PLAYER_SCORE'
export const PLAYER_LEADERBOARD = 'PLAYER_LEADERBOARD'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
